# Foundations & Tensor Operations

## Assignment Number : 1

- Student Name: Sanjay Pahari
- Roll Number: 42
- Date: 05 April 2026
- Dataset Used: None
- Resource Utilized: d2l.ai

## Objective
This assigment focuses on foundations of ML & Tensor Operations. Below are some objectives that this assingments would achieve:

1. Basics of the ML
2. Basic setup understanding of Jupyter Notebook and collab
3. Tensor Operation in ML 
4. Numpy vs Pythorch Comparison
5. Matrix Algebra & Computation
6. Numerical Satability Analysis

## Theoretical Background

Some of the topics need to understand are: 

1. Tensor: Tensor give us a generic way of describing extension to n^th-order array. It can represent large dimesional data.
2. Matrices: 0th order tensors are known as scalar. 1st order tensors are known as vector. 2nd order tensors are known as matrices. 
3. Eigenvalues & Eigenvector: Eigen vectors are those vectors that doesn't change the direction in a transformation.

![alt text](./assets/2026-04-05_14-56.png "Title")

Mathematically, they are represented as 

![alt text](./assets/2026-04-05_15-00.png)

4. NumPy and PyTorch:

NumPy is the fundamental package for scientific computing which is availabe as a python library that even works for multidimensional array data calculation.

PyTorch is a deep learning library built on Python which provides GPU acceleration and dynamic computation graphs.

# Implementation

The implementations are divided into several parts:

First run this library importing code block

In [70]:
# Initialization

import numpy as np
import torch



## Part I

### Tensor Operations

In [71]:
# tensor operations (creation, reshaping, broadcasting)

######################
# tensor creation
######################

# numpy tensor initialization
a_numpy = np.array([[1, 2, 3], [4, 5, 6]])
b_numpy =  np.array([[7, 8, 9], [10, 11, 12]])

# pytorch tensor initialization
a_torch = torch.tensor([[1, 2, 3], [4, 5, 6]])
b_torch = torch.tensor([[7, 8, 9], [10, 11, 12]])

print(f"\n numpy tensor: {a_numpy} \n")
print(f"\n torch tensor: {a_torch} \n")

######################
# Manual
######################

# mannual creation as a list
manual_tensor = [
    [1, 2, 3],
    [4, 5, 6]
]

print(f"\n manual tensor: {manual_tensor} \n")


 numpy tensor: [[1 2 3]
 [4 5 6]] 


 torch tensor: tensor([[1, 2, 3],
        [4, 5, 6]]) 


 manual tensor: [[1, 2, 3], [4, 5, 6]] 



In [72]:
######################
# Tensor Reshaping
######################

a_numpy_tensor = np.array([1,2,3,4,5,6])

# Numpy tensor reshaped
reshaped_a_numpy = a_numpy_tensor.reshape(2,3)

a_torch_tensor = torch.tensor([1,2,3,4,5,6])

# Pytorch tensor reshaped
reshaped_a_torch = a_torch_tensor.reshape(2,3)

print(f"\n numpy_tensor a: {a_numpy_tensor} \n")
print(f"\n Reshaped Numpy Tensor: {reshaped_a_numpy} \n")
print(f"\n pytorch_tensor a: {a_torch_tensor} \n")
print(f"\n Reshaped Torch Tensor: {reshaped_a_torch} \n")

######################
# Manual
######################

# manual tensor
manual_tensor = [
    [1, 2, 3],
    [4, 5, 6]
]

# tranfer each manual tensor elements into a single list
flat_list = []
for row in manual_tensor:
    for elements in row:
        flat_list.append(elements)

# Reshape into 3x2 tensor
reshaped_manual = []
rows, cols = 3, 2
for i in range(rows): # range generate 0 to 2
    start_index = i*cols 
    end_index = start_index +cols
    row = flat_list[start_index:end_index]
    reshaped_manual.append(row)

print(f"\n manual_tensor a: {manual_tensor} \n")
print(f"\n Reshaped Manual Tensor: {reshaped_manual} \n")


 numpy_tensor a: [1 2 3 4 5 6] 


 Reshaped Numpy Tensor: [[1 2 3]
 [4 5 6]] 


 pytorch_tensor a: tensor([1, 2, 3, 4, 5, 6]) 


 Reshaped Torch Tensor: tensor([[1, 2, 3],
        [4, 5, 6]]) 


 manual_tensor a: [[1, 2, 3], [4, 5, 6]] 


 Reshaped Manual Tensor: [[1, 2], [3, 4], [5, 6]] 



In [73]:
######################
# Tensor Broadcasting
######################
'''  
Broadcasting means operation between two tensor of different dimension. 
Simply, it means copying the smallest tensor to match the dimension of the largest tensor

Constraint: column of first tensor much be same of another or one should be 1 to be stretched

Here, first, I will try 2 different tensor 
initialized from pytorch and numpy 
with different dimension.
'''

a_numpy_tensor = np.array([[1,2,3],[4,5,6]])
b_pytorch_tensor = torch.tensor([10,20,30])
b_numpy_tensor = np.array([10,20,30])

# Not possible
# broadcasted_result = a_numpy_tensor + b_pytorch_tensor

broadcasted_result = a_numpy_tensor + b_numpy_tensor

print(f"\n Numpy a Tensor: {a_numpy_tensor} \n")
print(f"\n Numpy b Tensor: {b_numpy_tensor} \n")
print(f"\n broadcasted_result: {broadcasted_result} \n")

######################
# Manual
######################

# manual tensor
a_manual_tensor = [
    [1, 2, 3],
    [4, 5, 6]
]
b_manual_tensor = [10, 20, 30]
broadcasted_manual_result = []

# This is hard coded. This logic is not generic for other dimension tension.
for row in a_manual_tensor:
    new_row = []
    for i in range(len(row)):
        new_row.append(row[i] + b_manual_tensor[i]) # add element of smallest tensor to largest one
    broadcasted_manual_result.append(new_row)

print(f"\n Manual Tensor a: {a_manual_tensor} \n")
print(f"\n Manual Tensor b: {b_manual_tensor} \n")
print(f"\n broadcasted_result: {broadcasted_manual_result} \n")


 Numpy a Tensor: [[1 2 3]
 [4 5 6]] 


 Numpy b Tensor: [10 20 30] 


 broadcasted_result: [[11 22 33]
 [14 25 36]] 


 Manual Tensor a: [[1, 2, 3], [4, 5, 6]] 


 Manual Tensor b: [10, 20, 30] 


 broadcasted_result: [[11, 22, 33], [14, 25, 36]] 



## Part II

### Matrix Operation

In [74]:
######################
# Matrix Operation (Multiplication)
######################
'''  
Matrix Multiplication can be done using @ opeartor which is Pythonic.
Also using matmul(a,b), works with higher dimension 
'''

# Numpy matrix definition
a_numpy = np.array([[1, 2, 3], 
                    [4, 5, 6]])
b_numpy =  np.array([[7, 8, 9], 
                     [10, 11, 12]])
numpy_operation = a_numpy @ b_numpy.T # Transposing to make valid size for multiplication

# Pytorch matrix definition
a_torch = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
b_torch = torch.tensor([[7, 8, 9], 
                        [10, 11, 12]])
pytorch_operation = a_torch @ b_torch.T


print(f"\n Numpy a Tensor: {a_numpy} \n")
print(f"\n Pytorch b Tensor: {b_torch} \n")
print(f"\n Numpy Matrix Muliplication Result: {numpy_operation} \n")
print(f"\n Pytorch Matrix Muliplication Result: {pytorch_operation} \n")


 Numpy a Tensor: [[1 2 3]
 [4 5 6]] 


 Pytorch b Tensor: tensor([[ 7,  8,  9],
        [10, 11, 12]]) 


 Numpy Matrix Muliplication Result: [[ 50  68]
 [122 167]] 


 Pytorch Matrix Muliplication Result: tensor([[ 50,  68],
        [122, 167]]) 



In [75]:
######################
# Eigen Value
######################
'''
Pytorch return eigen value and vector in complex form to reduce error.
If is for safety reason and note to know that complex number are superset of real numbers
'''

# Numpy matrix definition
a_numpy = np.array([[1, 2, 3], 
                    [4, 5, 6],
                    [4, 5, 6]])
# Compute eigenvalues and eigenvectors
eigvals_numpy, eigvecs_numpy = np.linalg.eig(a_numpy)


# Pytorch matrix definition
a_torch = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [4, 5, 6]], dtype=torch.float32)
eigvals_torch, eigvecs_torch = torch.linalg.eig(a_torch)


print(f"\n Numpy Tensor a: {a_numpy} \n")
print(f"\n Pytorch Tensor a: {a_torch} \n")
print("\nNumPy Eigenvalues:\n", eigvals_numpy)
print("\nNumPy Eigenvectors:\n", eigvecs_numpy)
print("\nTorch Eigenvalues:\n", eigvals_torch)
print("\nTorch Eigenvectors:\n", eigvecs_torch)


 Numpy Tensor a: [[1 2 3]
 [4 5 6]
 [4 5 6]] 


 Pytorch Tensor a: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.]]) 


NumPy Eigenvalues:
 [ 1.27082039e+01 -7.08203932e-01 -5.28385524e-17]

NumPy Eigenvectors:
 [[ 0.28907816  0.90041255  0.40824829]
 [ 0.67691721 -0.30761765 -0.81649658]
 [ 0.67691721 -0.30761765  0.40824829]]

Torch Eigenvalues:
 tensor([ 1.2708e+01+0.j, -7.0820e-01+0.j,  3.9329e-08+0.j])

Torch Eigenvectors:
 tensor([[ 0.2891+0.j,  0.9004+0.j,  0.4082+0.j],
        [ 0.6769+0.j, -0.3076+0.j, -0.8165+0.j],
        [ 0.6769+0.j, -0.3076+0.j,  0.4082+0.j]])


## Part III

### Numerical Instability and Precision Analysis

Computers can't represent all the numbers exactly. There is error especially in large sums,nearly equal number and matrix operation with very small or very large number due to round off.

In [76]:
##############################################
# Numerical Precision Analysis
##############################################
''' 
This example shows how large number can loss the precesion when
data type is not set properly. For an example: float32 won't able to 
compute for precise solution for larger value. Below is the simple
example code.
'''

# Numpy scalar definition
a_numpy = np.array(1e10 + 1, dtype=np.float32)
b_numpy = np.array(1e10, dtype=np.float32)

difference_numpy = a_numpy - b_numpy

# Pytorch scalar definition
a_torch = torch.tensor(1e10 + 1, dtype=torch.float64)
b_torch = torch.tensor(1e10, dtype=torch.float64)

difference_torch = a_torch - b_torch

print(f"\n Numpy a: {a_numpy} \n Numpy b: {b_numpy} \n")
print(f"\nNumpy difference: {difference_numpy}\n")
print(f"\nDue to float32 data type the result is 0 which is not precise, the correct precise answer is 1\n")
print(f"\n Torch a: {a_torch} \n Torch b: {b_torch} \n")
print(f"\n Pytorch difference: {difference_torch} \n")


 Numpy a: 10000000000.0 
 Numpy b: 10000000000.0 


Numpy difference: 0.0


Due to float32 data type the result is 0 which is not precise, the correct precise answer is 1


 Torch a: 10000000001.0 
 Torch b: 10000000000.0 


 Pytorch difference: 1.0 



In [77]:
##############################################
# Numerical Instability Analysis
##############################################
''' 
This example shows how large number can raise the instability 
in the calculation. Below is the simple example code of matrix
multiplication in which large value caused the instability.
'''

# Numpy matrix definition
a_numpy = np.array([[1e10,1],[1,1.0000001]]) # by default float64 datatype
b_numpy = np.array([[1,1],[1,1]])

result_numpy = np.linalg.inv(a_numpy) @ b_numpy

# Pytorch matrix definition
a_torch = torch.tensor([[1e10, 1], [1, 1.0000001]], dtype=torch.float32)
b_torch = torch.tensor([[1, 1], [1, 1]], dtype=torch.float32)

result_torch = torch.linalg.inv(a_torch) @ b_torch

print(f"\n Numpy a: {a_numpy} \n Numpy b: {b_numpy} \n")
print(f"\nNumpy Operation Result: {result_numpy}\n")
print(f"\nInstability in calculation due to data type difference as there is very small number difference in two output\n")
print(f"\n Torch a: {a_torch} \n Torch b: {b_torch} \n")
print(f"\n Pytorch Operation Result: {result_torch} \n")


 Numpy a: [[1.0000000e+10 1.0000000e+00]
 [1.0000000e+00 1.0000001e+00]] 
 Numpy b: [[1 1]
 [1 1]] 


Numpy Operation Result: [[9.99999901e-18 9.99999901e-18]
 [9.99999900e-01 9.99999900e-01]]


Instability in calculation due to data type difference as there is very small number difference in two output


 Torch a: tensor([[1.0000e+10, 1.0000e+00],
        [1.0000e+00, 1.0000e+00]]) 
 Torch b: tensor([[1., 1.],
        [1., 1.]]) 


 Pytorch Operation Result: tensor([[1.3878e-17, 1.3878e-17],
        [1.0000e+00, 1.0000e+00]]) 



## Part IV

### Interpretation of tensor operations in ML context

Based on the operation that are implemented in this assigment, below are the interpretation them in ML context:
1. Tensor Creation: Tensor store input data like features, images, text embeddings and so on in multi-dimensional data object. E.g. RGP pixel property [122,124,133].
2. Tensor Reshaping: It is used in ML for preparing data to use in models. E.g. in CNN images are flattened (making shape (1,n)) before feeding into fully connected layers.
3. Tensor Broadcasting: It is used to apply operations across batches withut loops. E.g. adding bias in neural networks (output = input_tensor + bias) where bias vector is automatically broadcasted to all rows

# Dataset Description

This assigment doesn't use any dataset.

# Experiements

This assignment doesn't involve writing an advance code consisting of hyperparameters and configuration.


# Results

The ouput of operation applied on tensors and matrices can be printed by running any of the code block written above. 

# Analysis & Discussion

The various approaches to writting code result in different outcomes. 

# Conclusion

The following points highlight key insights from this assignment:
1. The data type difference could result in imprecision output.
2. Pytorch runs calculation offering GPU acceleration whereas NumPy runs calculations on CPU only.
3. Pytorch and NumPy generates different data type object speratly which also restrict operation between them.
4. Manual approaches result in larger codebase whereas libraries make codebase consise and readable.
5. Code should be written to handle instability and imprecision, especially in scientific research projects.